#!/usr/bin/env python3
"""
Unified dashboard: Portfolio holdings + Backtest results in a single HTML file.

Reads:
  - backtest_output/trades.csv (holdings for portfolio tab)
  - backtest_output/dashboard_data.json (backtest results, generated by backtest.py)

Run: python3 portfolio_view.py
Output: backtest_output/dashboard.html
"""

import json
import warnings
import numpy as np
import pandas as pd
import yfinance as yf
from datetime import datetime

warnings.filterwarnings("ignore")

OUTPUT_DIR = "backtest_output"
TRADES_CSV = f"{OUTPUT_DIR}/trades.csv"
BACKTEST_JSON = f"{OUTPUT_DIR}/dashboard_data.json"
STRATEGY = "Timed HODL"


# ─── Portfolio data ────────────────────────────────────────────────────────

def load_holdings():
    df = pd.read_csv(TRADES_CSV, parse_dates=["date"])
    df = df[df["strategy"] == STRATEGY].copy()
    df["shares"] = df["amount"] / df["price"]

    holdings = df.groupby("stock").agg(
        total_invested=("amount", "sum"),
        total_shares=("shares", "sum"),
        num_buys=("amount", "count"),
        first_buy=("date", "min"),
        last_buy=("date", "max"),
    ).reset_index()
    holdings["avg_price"] = holdings["total_invested"] / holdings["total_shares"]

    trades_by_stock = {}
    for stock, group in df.groupby("stock"):
        trades_by_stock[stock] = group[["date", "price", "amount"]].to_dict("records")

    return holdings, trades_by_stock


def fetch_current_prices(stocks):
    tickers = [f"{s}.NS" for s in stocks]
    data = yf.download(tickers, period="5d", interval="1d", progress=False)
    prices = {}
    for stock in stocks:
        ticker = f"{stock}.NS"
        try:
            if isinstance(data.columns, pd.MultiIndex):
                col = data["Close"][ticker].dropna()
            else:
                col = data["Close"].dropna()
            prices[stock] = float(col.iloc[-1])
        except (KeyError, IndexError):
            prices[stock] = np.nan
    return prices


def build_portfolio(holdings, prices):
    holdings["current_price"] = holdings["stock"].map(prices)
    holdings["current_value"] = holdings["total_shares"] * holdings["current_price"]
    holdings["pnl"] = holdings["current_value"] - holdings["total_invested"]
    holdings["return_pct"] = (holdings["pnl"] / holdings["total_invested"]) * 100
    holdings["weight_pct"] = (holdings["current_value"] / holdings["current_value"].sum()) * 100
    return holdings.sort_values("current_value", ascending=False).reset_index(drop=True)


def build_portfolio_json(p, trades_by_stock):
    total_invested = p["total_invested"].sum()
    total_value = p["current_value"].sum()
    total_pnl = total_value - total_invested
    total_ret = (total_pnl / total_invested) * 100
    winners = int((p["pnl"] > 0).sum())
    losers = int((p["pnl"] <= 0).sum())
    best = p.loc[p["return_pct"].idxmax()]
    worst = p.loc[p["return_pct"].idxmin()]

    rows = []
    for _, r in p.iterrows():
        stock = r["stock"]
        trades = trades_by_stock.get(stock, [])
        trade_rows = ""
        for t in trades:
            d = t["date"].strftime("%Y-%m-%d") if hasattr(t["date"], "strftime") else str(t["date"])[:10]
            shares = t["amount"] / t["price"]
            trade_rows += f"<tr><td>{d}</td><td>₹{t['price']:.2f}</td><td>{shares:.1f}</td><td>₹{t['amount']:,.0f}</td></tr>"

        rows.append({
            "stock": stock,
            "avg_price": round(r["avg_price"], 2),
            "cmp": round(r["current_price"], 2),
            "shares": round(r["total_shares"], 1),
            "invested": round(r["total_invested"]),
            "value": round(r["current_value"]),
            "pnl": round(r["pnl"]),
            "ret": round(r["return_pct"], 1),
            "weight": round(r["weight_pct"], 1),
            "num_buys": int(r["num_buys"]),
            "first_buy": r["first_buy"].strftime("%Y-%m-%d"),
            "last_buy": r["last_buy"].strftime("%Y-%m-%d"),
            "trade_rows": trade_rows,
        })

    top_n = 10
    alloc_labels = list(p.head(top_n)["stock"])
    alloc_values = list(p.head(top_n)["current_value"].round(0))
    if len(p) > top_n:
        alloc_labels.append("Others")
        alloc_values.append(round(p.iloc[top_n:]["current_value"].sum()))

    pnl_sorted = p.sort_values("pnl", ascending=True)

    return {
        "rows": rows,
        "summary": {
            "total_invested": round(total_invested),
            "total_value": round(total_value),
            "total_pnl": round(total_pnl),
            "total_ret": round(total_ret, 1),
            "winners": winners,
            "losers": losers,
            "best_stock": best["stock"],
            "best_ret": round(best["return_pct"]),
            "worst_stock": worst["stock"],
            "worst_ret": round(worst["return_pct"]),
            "count": len(p),
        },
        "alloc_labels": alloc_labels,
        "alloc_values": [float(v) for v in alloc_values],
        "pnl_labels": list(pnl_sorted["stock"]),
        "pnl_values": [float(v) for v in pnl_sorted["pnl"].round(0)],
    }


# ─── HTML generation ──────────────────────────────────────────────────────

def fmt_inr(v):
    if abs(v) >= 1e5:
        return f"₹{v/1e5:.2f}L"
    return f"₹{v:,.0f}"


def generate_html(portfolio_data, backtest_data):
    ps = portfolio_data["summary"]
    has_backtest = backtest_data is not None

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HODL Bot Dashboard</title>
<style>
:root {{
  --bg: #0f0f1a; --card: #1a1a2e; --border: #2a2a3e;
  --text: #e0e0e0; --muted: #888; --green: #4CAF50; --red: #F44336;
  --blue: #2196F3; --accent: #7c4dff; --orange: #FF9800; --purple: #9C27B0; --pink: #E91E63;
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; }}
.header {{ padding: 20px 24px 0; text-align: center; }}
.header h1 {{ font-size: 1.6rem; color: #fff; }}
.header .sub {{ color: var(--muted); font-size: 0.82rem; margin-top: 4px; }}

/* Tabs */
.tabs {{ display: flex; justify-content: center; gap: 4px; margin: 16px 24px 0; }}
.tab {{
  padding: 10px 28px; border-radius: 8px 8px 0 0; cursor: pointer; font-size: 0.9rem;
  font-weight: 600; background: var(--card); color: var(--muted); border: 1px solid var(--border);
  border-bottom: none; transition: all 0.2s;
}}
.tab:hover {{ color: var(--text); }}
.tab.active {{ background: var(--bg); color: #fff; border-color: var(--accent); border-bottom: 2px solid var(--bg); }}
.tab-content {{ display: none; padding: 20px 24px; }}
.tab-content.active {{ display: block; }}

/* Common */
.summary-grid {{
  display: grid; grid-template-columns: repeat(auto-fit, minmax(170px, 1fr));
  gap: 12px; margin-bottom: 20px;
}}
.stat-card {{
  background: var(--card); border: 1px solid var(--border); border-radius: 10px;
  padding: 14px; text-align: center;
}}
.stat-card .label {{ color: var(--muted); font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.5px; }}
.stat-card .value {{ font-size: 1.3rem; font-weight: 700; margin-top: 3px; }}
.charts-row {{ display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-bottom: 20px; }}
.charts-row.triple {{ grid-template-columns: 1fr 1fr 1fr; }}
.chart-card {{
  background: var(--card); border: 1px solid var(--border); border-radius: 10px;
  padding: 16px; overflow: hidden;
}}
.chart-card.wide {{ grid-column: span 2; }}
.chart-card.full {{ grid-column: 1 / -1; }}
.chart-card h3 {{ color: #fff; font-size: 0.9rem; margin-bottom: 10px; }}
.chart-card .chart-sub {{ color: var(--muted); font-size: 0.75rem; margin-top: -6px; margin-bottom: 10px; }}
canvas {{ width: 100% !important; }}
.positive {{ color: var(--green); }}
.negative {{ color: var(--red); }}

/* Table */
.controls {{ display: flex; gap: 10px; margin-bottom: 14px; align-items: center; flex-wrap: wrap; }}
.controls input, .controls select {{
  background: var(--card); border: 1px solid var(--border); border-radius: 6px;
  color: var(--text); padding: 7px 11px; font-size: 0.82rem;
}}
.controls input {{ width: 220px; }}
.table-wrap {{
  background: var(--card); border: 1px solid var(--border); border-radius: 10px;
  overflow-x: auto;
}}
table {{ width: 100%; border-collapse: collapse; font-size: 0.8rem; }}
th {{
  background: #16213e; color: var(--muted); font-weight: 600; text-transform: uppercase;
  font-size: 0.68rem; letter-spacing: 0.5px; padding: 9px 10px; text-align: right;
  position: sticky; top: 0; cursor: pointer; user-select: none;
}}
th:first-child {{ text-align: left; }}
th[title] {{ cursor: help; }}
td {{ padding: 8px 10px; border-top: 1px solid var(--border); text-align: right; white-space: nowrap; }}
td:first-child {{ text-align: left; font-weight: 600; color: #fff; }}
tr:hover {{ background: #ffffff08; }}
tr.total-row {{ background: #16213e; font-weight: 700; }}
tr.total-row td {{ border-top: 2px solid var(--border); }}
.stock-link {{ cursor: pointer; text-decoration: underline dotted; text-underline-offset: 3px; }}
.bar {{ height: 5px; border-radius: 3px; display: inline-block; vertical-align: middle; min-width: 3px; }}
.weight-cell {{ display: flex; align-items: center; justify-content: flex-end; gap: 5px; }}

/* Metrics table (backtest) */
.metrics-table {{ width: 100%; font-size: 0.82rem; }}
.metrics-table th {{ text-align: center; padding: 10px 8px; font-size: 0.75rem; }}
.metrics-table th.row-label {{ text-align: right; background: var(--card); min-width: 160px; }}
.metrics-table td {{ text-align: center; padding: 9px 8px; }}
.metrics-table td.row-label {{ text-align: right; color: var(--muted); font-weight: 600; font-size: 0.75rem; }}
.metrics-table tr:nth-child(even) td {{ background: #ffffff04; }}
.metrics-best {{ font-weight: 700; }}

/* Assumptions banner */
.assumptions {{
  background: var(--card); border: 1px solid var(--border); border-radius: 10px;
  padding: 14px 20px; margin-bottom: 20px; font-size: 0.82rem; color: var(--muted);
  line-height: 1.7;
}}
.assumptions strong {{ color: var(--text); }}

/* Backtest tile grid */
.bt-grid {{
  display: grid; grid-template-columns: repeat(2, 1fr);
  gap: 14px; margin-bottom: 14px;
}}
.bt-grid .bt-tile.full {{ grid-column: 1 / -1; }}
.bt-tile {{
  background: var(--card); border: 1px solid var(--border); border-radius: 10px;
  padding: 14px 16px; position: relative; cursor: zoom-in;
  transition: transform 0.15s, border-color 0.15s, box-shadow 0.15s;
  display: flex; flex-direction: column;
}}
.bt-tile:hover {{
  border-color: var(--accent);
  box-shadow: 0 4px 16px rgba(124,77,255,0.15);
  transform: translateY(-2px);
}}
.bt-tile h3 {{ color: #fff; font-size: 0.88rem; margin-bottom: 4px; padding-right: 24px; }}
.bt-tile .chart-sub {{ color: var(--muted); font-size: 0.72rem; margin-bottom: 8px; }}
.bt-tile .zoom-icon {{
  position: absolute; top: 12px; right: 12px;
  color: var(--muted); font-size: 1rem; pointer-events: none;
  transition: color 0.15s;
}}
.bt-tile:hover .zoom-icon {{ color: var(--accent); }}
.bt-tile .chart-wrap {{ position: relative; flex: 1; min-height: 240px; height: 240px; }}
.bt-tile.tall .chart-wrap {{ min-height: 340px; height: 340px; }}

/* Modal */
.modal-overlay {{
  display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%;
  background: rgba(0,0,0,0.85); z-index: 100; justify-content: center; align-items: center;
  padding: 24px;
}}
.modal-overlay.active {{ display: flex; }}
.modal {{
  background: var(--card); border: 1px solid var(--border); border-radius: 12px;
  padding: 22px; max-width: 520px; width: 90%; max-height: 80vh; overflow-y: auto;
}}
.modal h3 {{ color: #fff; margin-bottom: 14px; }}
.modal .close {{ float: right; cursor: pointer; color: var(--muted); font-size: 1.3rem; }}
.modal .close:hover {{ color: #fff; }}

/* Chart zoom modal */
.chart-modal {{
  background: var(--card); border: 1px solid var(--border); border-radius: 12px;
  padding: 22px 26px; width: 95vw; max-width: 1400px; height: 85vh;
  display: flex; flex-direction: column;
}}
.chart-modal .head {{ display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 10px; }}
.chart-modal h3 {{ color: #fff; font-size: 1.1rem; }}
.chart-modal .chart-sub {{ color: var(--muted); font-size: 0.82rem; margin-top: 2px; }}
.chart-modal .close {{ cursor: pointer; color: var(--muted); font-size: 1.6rem; padding: 0 8px; line-height: 1; }}
.chart-modal .close:hover {{ color: #fff; }}
.chart-modal .chart-wrap {{ flex: 1; position: relative; min-height: 0; }}

@media (max-width: 900px) {{
  .bt-grid {{ grid-template-columns: 1fr; }}
  .summary-grid {{ grid-template-columns: repeat(2, 1fr); }}
  .tab {{ padding: 8px 16px; font-size: 0.8rem; }}
  .chart-modal {{ height: 80vh; padding: 16px; }}
}}
</style>
</head>
<body>

<div class="header">
  <h1>HODL Bot Dashboard</h1>
  <div class="sub">Updated {datetime.now().strftime('%d %b %Y, %I:%M %p')}</div>
</div>

<div class="tabs">
  <div class="tab active" onclick="switchTab('portfolio')">Portfolio</div>
  {'''<div class='tab' onclick="switchTab('backtest')">Backtest</div>''' if has_backtest else ""}
</div>

<!-- ═══ PORTFOLIO TAB ═══ -->
<div id="tab-portfolio" class="tab-content active">
  <div class="summary-grid">
    <div class="stat-card">
      <div class="label">Total Invested</div>
      <div class="value" style="color:var(--blue)">{fmt_inr(ps['total_invested'])}</div>
    </div>
    <div class="stat-card">
      <div class="label">Current Value</div>
      <div class="value">{fmt_inr(ps['total_value'])}</div>
    </div>
    <div class="stat-card">
      <div class="label">Total P&L</div>
      <div class="value {'positive' if ps['total_pnl']>=0 else 'negative'}">
        {'+' if ps['total_pnl']>=0 else ''}{fmt_inr(ps['total_pnl'])} ({ps['total_ret']:+.1f}%)</div>
    </div>
    <div class="stat-card">
      <div class="label">Winners / Losers</div>
      <div class="value"><span class="positive">{ps['winners']}</span> / <span class="negative">{ps['losers']}</span></div>
    </div>
    <div class="stat-card">
      <div class="label">Best</div>
      <div class="value positive" style="font-size:1rem">{ps['best_stock']} ({ps['best_ret']:+,}%)</div>
    </div>
    <div class="stat-card">
      <div class="label">Worst</div>
      <div class="value negative" style="font-size:1rem">{ps['worst_stock']} ({ps['worst_ret']:+,}%)</div>
    </div>
  </div>

  <div class="charts-row">
    <div class="chart-card"><h3>P&L by Stock</h3><canvas id="pf_pnlChart" height="300"></canvas></div>
    <div class="chart-card"><h3>Portfolio Allocation</h3><canvas id="pf_allocChart" height="300"></canvas></div>
  </div>

  <div class="controls">
    <input type="text" id="pf_search" placeholder="Search stocks..." oninput="pfFilterTable()">
    <select id="pf_sort" onchange="pfSortTable()">
      <option value="value-desc">Value (High-Low)</option>
      <option value="pnl-desc">P&L (High-Low)</option>
      <option value="ret-desc">Return % (High-Low)</option>
      <option value="ret-asc">Return % (Low-High)</option>
      <option value="invested-desc">Invested (High-Low)</option>
      <option value="weight-desc">Weight (High-Low)</option>
      <option value="stock-asc">Name (A-Z)</option>
    </select>
  </div>
  <div class="table-wrap">
    <table><thead><tr>
      <th>Stock</th><th>Avg Price</th><th>CMP</th><th>Shares</th>
      <th>Invested</th><th>Value</th><th>P&L</th><th>Return %</th>
      <th title="Current value of this stock as a % of total portfolio value. Shows how concentrated your portfolio is in each holding.">Weight &#9432;</th>
    </tr></thead><tbody id="pf_tbody"></tbody></table>
  </div>
</div>

<!-- ═══ BACKTEST TAB ═══ -->
<div id="tab-backtest" class="tab-content">
  <div id="bt_content"></div>
</div>

<!-- Trade history modal -->
<div class="modal-overlay" id="modalOverlay" onclick="if(event.target===this)closeModal()">
  <div class="modal">
    <span class="close" onclick="closeModal()">&times;</span>
    <h3 id="modalTitle"></h3>
    <div id="modalStats" style="margin-bottom:12px;font-size:0.82rem;color:var(--muted);"></div>
    <table><thead><tr><th>Date</th><th>Price</th><th>Shares</th><th>Amount</th></tr></thead>
    <tbody id="modalTrades"></tbody></table>
  </div>
</div>

<!-- Chart zoom modal -->
<div class="modal-overlay" id="chartModalOverlay" onclick="if(event.target===this)closeChartModal()">
  <div class="chart-modal">
    <div class="head">
      <div>
        <h3 id="chartModalTitle"></h3>
        <div class="chart-sub" id="chartModalSub"></div>
      </div>
      <span class="close" onclick="closeChartModal()">&times;</span>
    </div>
    <div class="chart-wrap"><canvas id="chartModalCanvas"></canvas></div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
// ─── Shared ───
function fmtInr(v) {{
  if (Math.abs(v) >= 1e5) return '₹' + (v/1e5).toFixed(2) + 'L';
  return '₹' + v.toLocaleString('en-IN');
}}

function switchTab(id) {{
  document.querySelectorAll('.tab').forEach(t => t.classList.remove('active'));
  document.querySelectorAll('.tab-content').forEach(t => t.classList.remove('active'));
  document.getElementById('tab-' + id).classList.add('active');
  event.target.classList.add('active');
  if (id === 'backtest' && !window._btRendered) renderBacktest();
}}

function openModal(stock) {{
  const r = PF_DATA.find(d => d.stock === stock);
  document.getElementById('modalTitle').textContent = r.stock;
  const pc = r.pnl >= 0 ? 'positive' : 'negative';
  document.getElementById('modalStats').innerHTML =
    `${{r.num_buys}} buys &bull; ${{r.first_buy}} to ${{r.last_buy}}<br>` +
    `Avg: ₹${{r.avg_price.toFixed(2)}} &bull; CMP: ₹${{r.cmp.toFixed(2)}} &bull; ` +
    `P&L: <span class="${{pc}}">${{r.pnl>=0?'+':''}}${{fmtInr(r.pnl)}} (${{r.ret>0?'+':''}}${{r.ret.toFixed(1)}}%)</span>`;
  document.getElementById('modalTrades').innerHTML = r.trade_rows;
  document.getElementById('modalOverlay').classList.add('active');
}}
function closeModal() {{ document.getElementById('modalOverlay').classList.remove('active'); }}
document.addEventListener('keydown', e => {{
  if (e.key==='Escape') {{ closeModal(); closeChartModal(); }}
}});

// ─── Portfolio Tab ───
const PF_DATA = {json.dumps(portfolio_data['rows'])};
const PF_ALLOC_LABELS = {json.dumps(portfolio_data['alloc_labels'])};
const PF_ALLOC_VALUES = {json.dumps(portfolio_data['alloc_values'])};
const PF_PNL_LABELS = {json.dumps(portfolio_data['pnl_labels'])};
const PF_PNL_VALUES = {json.dumps(portfolio_data['pnl_values'])};
const pfMaxWeight = Math.max(...PF_DATA.map(d => d.weight));

function pfRenderTable(data) {{
  const tb = document.getElementById('pf_tbody');
  let html = '', totI = 0, totV = 0;
  data.forEach(r => {{
    totI += r.invested; totV += r.value;
    const c = r.pnl >= 0 ? 'positive' : 'negative';
    const s = r.pnl >= 0 ? '+' : '';
    const bw = (r.weight / pfMaxWeight * 55).toFixed(0);
    const bc = r.pnl >= 0 ? 'var(--green)' : 'var(--red)';
    html += `<tr>
      <td><span class="stock-link" onclick="openModal('${{r.stock}}')">${{r.stock}}</span></td>
      <td>₹${{r.avg_price.toFixed(2)}}</td><td>₹${{r.cmp.toFixed(2)}}</td>
      <td>${{r.shares.toFixed(1)}}</td><td>${{fmtInr(r.invested)}}</td><td>${{fmtInr(r.value)}}</td>
      <td class="${{c}}">${{s}}${{fmtInr(r.pnl)}}</td><td class="${{c}}">${{s}}${{r.ret.toFixed(1)}}%</td>
      <td><div class="weight-cell">${{r.weight.toFixed(1)}}%<span class="bar" style="width:${{bw}}px;background:${{bc}}"></span></div></td>
    </tr>`;
  }});
  const tp = totV - totI, tr2 = tp/totI*100, tc = tp>=0?'positive':'negative', ts = tp>=0?'+':'';
  html += `<tr class="total-row"><td>TOTAL (${{data.length}})</td><td></td><td></td><td></td>
    <td>${{fmtInr(totI)}}</td><td>${{fmtInr(totV)}}</td>
    <td class="${{tc}}">${{ts}}${{fmtInr(tp)}}</td><td class="${{tc}}">${{ts}}${{tr2.toFixed(1)}}%</td><td>100%</td></tr>`;
  tb.innerHTML = html;
}}
function pfFilterTable() {{
  const q = document.getElementById('pf_search').value.toLowerCase();
  pfRenderTable(PF_DATA.filter(r => r.stock.toLowerCase().includes(q)));
}}
function pfSortTable() {{
  const [col, dir] = document.getElementById('pf_sort').value.split('-');
  const m = dir === 'asc' ? 1 : -1;
  const s = [...PF_DATA].sort((a,b) => col==='stock' ? m*a.stock.localeCompare(b.stock) : m*(a[col]-b[col]));
  pfRenderTable(s);
}}
pfRenderTable(PF_DATA);

const DONUT_COLORS = ['#4CAF50','#2196F3','#FF9800','#9C27B0','#E91E63','#00BCD4','#FFC107','#795548','#607D8B','#8BC34A','#CDDC39'];

new Chart(document.getElementById('pf_pnlChart'), {{
  type: 'bar',
  data: {{ labels: PF_PNL_LABELS, datasets: [{{
    data: PF_PNL_VALUES,
    backgroundColor: PF_PNL_VALUES.map(v => v>=0 ? '#4CAF5099' : '#F4433699'),
    borderColor: PF_PNL_VALUES.map(v => v>=0 ? '#4CAF50' : '#F44336'),
    borderWidth: 1
  }}] }},
  options: {{ indexAxis:'y', responsive:true,
    plugins: {{ legend:{{display:false}}, tooltip:{{callbacks:{{label:c=>fmtInr(c.raw)}}}} }},
    scales: {{ x:{{ticks:{{color:'#888',callback:v=>fmtInr(v)}},grid:{{color:'#ffffff10'}}}},
               y:{{ticks:{{color:'#ccc',font:{{size:9}}}},grid:{{display:false}}}} }}
  }}
}});

new Chart(document.getElementById('pf_allocChart'), {{
  type: 'doughnut',
  data: {{ labels: PF_ALLOC_LABELS, datasets: [{{
    data: PF_ALLOC_VALUES, backgroundColor: DONUT_COLORS,
    borderColor: '#1a1a2e', borderWidth: 2
  }}] }},
  options: {{ responsive:true, cutout:'55%',
    plugins: {{ legend:{{position:'right',labels:{{color:'#ccc',font:{{size:10}},padding:8}}}},
      tooltip:{{callbacks:{{label:c=>`${{c.label}}: ${{fmtInr(c.raw)}} (${{(c.raw/PF_ALLOC_VALUES.reduce((a,b)=>a+b,0)*100).toFixed(1)}}%)`}}}}
    }}
  }}
}});

// ─── Backtest Tab ───
{"const BT = " + json.dumps(backtest_data) + ";" if has_backtest else "const BT = null;"}

window._btRendered = false;
window._btTileCharts = {{}};
window._chartModalInstance = null;

// Chart config factories — each returns a fresh {{type, data, options}} for Chart.js.
// Used for both compact tile view and the zoom modal.
function buildChartConfigs() {{
  if (!BT) return {{}};
  const colors = BT.strategy_colors;
  const cfgs = {{}};

  // Equity curves
  const eq = BT.equity;
  const eqOrder = Object.keys(eq);
  cfgs.equity = () => ({{
    type: 'line',
    data: {{ labels: eq[eqOrder[0]].dates, datasets: eqOrder.map(name => ({{
      label: name, data: eq[name].values,
      borderColor: colors[name]||'#ccc',
      borderWidth: name.includes('Timed HODL') ? 2.5 : 1.5,
      pointRadius: 0, fill: false,
      borderDash: name.includes('NIFTY') ? [5,3] : [],
    }})) }},
    options: {{ responsive:true, maintainAspectRatio:false, interaction:{{mode:'index',intersect:false}},
      plugins: {{ legend:{{labels:{{color:'#ccc',font:{{size:10}}}}}},
        tooltip:{{callbacks:{{label:c=>c.dataset.label+': '+fmtInr(c.raw)}}}} }},
      scales: {{ x:{{ticks:{{color:'#666',maxTicksLimit:12}},grid:{{color:'#ffffff08'}}}},
        y:{{ticks:{{color:'#888',callback:v=>fmtInr(v)}},grid:{{color:'#ffffff10'}}}} }}
    }}
  }});

  // Drawdowns
  const dd = BT.drawdowns;
  const ddOrder = Object.keys(dd);
  cfgs.drawdowns = () => ({{
    type: 'line',
    data: {{ labels: dd[ddOrder[0]].dates, datasets: ddOrder.map(name => ({{
      label: name, data: dd[name].values,
      borderColor: colors[name]||'#ccc', borderWidth: 1, pointRadius: 0,
      fill: true, backgroundColor: (colors[name]||'#ccc') + '22',
    }})) }},
    options: {{ responsive:true, maintainAspectRatio:false, interaction:{{mode:'index',intersect:false}},
      plugins: {{ legend:{{labels:{{color:'#ccc',font:{{size:10}}}}}},
        tooltip:{{callbacks:{{label:c=>c.dataset.label+': '+c.raw.toFixed(1)+'%'}}}} }},
      scales: {{ x:{{ticks:{{color:'#666',maxTicksLimit:12}},grid:{{color:'#ffffff08'}}}},
        y:{{ticks:{{color:'#888',callback:v=>v+'%'}},grid:{{color:'#ffffff10'}}}} }}
    }}
  }});

  // Regime returns
  cfgs.regime = () => ({{
    type: 'bar',
    data: {{
      labels: BT.regimes.map(r => r.regime),
      datasets: BT.regime_strategies.map(name => ({{
        label: name, data: BT.regimes.map(r => r[name] ?? null),
        backgroundColor: colors[name]||'#ccc',
      }}))
    }},
    options: {{ responsive:true, maintainAspectRatio:false,
      plugins: {{ legend:{{labels:{{color:'#ccc',font:{{size:10}}}}}},
        tooltip:{{callbacks:{{label:c=>c.dataset.label+': '+(c.raw??'N/A')+'%'}}}} }},
      scales: {{ x:{{ticks:{{color:'#aaa',font:{{size:9}}}},grid:{{display:false}}}},
        y:{{ticks:{{color:'#888',callback:v=>v+'%'}},grid:{{color:'#ffffff10'}}}} }}
    }}
  }});

  // Cash utilization
  const cashKeys = Object.keys(BT.cash_util);
  cfgs.cash = () => ({{
    type: 'line',
    data: {{ labels: BT.cash_util[cashKeys[0]].dates, datasets: cashKeys.map(name => ({{
      label: name, data: BT.cash_util[name].values,
      borderColor: colors[name]||'#ccc', borderWidth: 1.5, pointRadius: 0,
      fill: true, backgroundColor: (colors[name]||'#ccc') + '20',
    }})) }},
    options: {{ responsive:true, maintainAspectRatio:false, interaction:{{mode:'index',intersect:false}},
      plugins: {{ legend:{{labels:{{color:'#ccc',font:{{size:10}}}}}},
        tooltip:{{callbacks:{{label:c=>c.dataset.label+': '+c.raw.toFixed(0)+'%'}}}} }},
      scales: {{ x:{{ticks:{{color:'#666',maxTicksLimit:10}},grid:{{color:'#ffffff08'}}}},
        y:{{min:0,max:105,ticks:{{color:'#888',callback:v=>v+'%'}},grid:{{color:'#ffffff10'}}}} }}
    }}
  }});

  // Rolling alpha
  const alphaKeys = Object.keys(BT.rolling_alpha);
  cfgs.alpha = () => ({{
    type: 'line',
    data: {{
      labels: alphaKeys.length ? BT.rolling_alpha[alphaKeys[0]].dates : [],
      datasets: alphaKeys.map((k,i) => ({{
        label: k + ' Alpha (wins ' + BT.rolling_alpha[k].pct_win + '%)',
        data: BT.rolling_alpha[k].values,
        borderColor: i===0 ? '#4CAF50' : '#2196F3',
        borderWidth: 1.2, pointRadius: 0, fill: true,
        backgroundColor: i===0 ? '#4CAF5020' : '#2196F320',
      }}))
    }},
    options: {{ responsive:true, maintainAspectRatio:false,
      plugins: {{ legend:{{labels:{{color:'#ccc',font:{{size:10}}}}}},
        tooltip:{{callbacks:{{label:c=>c.dataset.label.split(' Alpha')[0]+' alpha: '+c.raw.toFixed(1)+'%'}}}} }},
      scales: {{ x:{{ticks:{{color:'#666',maxTicksLimit:10}},grid:{{color:'#ffffff08'}}}},
        y:{{ticks:{{color:'#888',callback:v=>v+'%'}},grid:{{color:'#ffffff10'}}}} }}
    }}
  }});

  // Buy distribution
  cfgs.buydist = () => ({{
    type: 'bar',
    data: {{
      labels: BT.buy_distribution.map(d => d[0]),
      datasets: [{{
        data: BT.buy_distribution.map(d => d[1]),
        backgroundColor: '#4CAF5099', borderColor: '#4CAF50', borderWidth: 1
      }}]
    }},
    options: {{ indexAxis:'y', responsive:true, maintainAspectRatio:false,
      plugins: {{ legend:{{display:false}} }},
      scales: {{ x:{{ticks:{{color:'#888'}},grid:{{color:'#ffffff10'}}}},
        y:{{ticks:{{color:'#ccc',font:{{size:9}}}},grid:{{display:false}}}} }}
    }}
  }});

  // Buy timeline
  cfgs.timeline = () => ({{
    type: 'bar',
    data: {{
      labels: BT.buy_timeline.map(d => d.month),
      datasets: [{{
        data: BT.buy_timeline.map(d => d.amount),
        backgroundColor: '#4CAF5044', borderColor: '#4CAF50', borderWidth: 1
      }}]
    }},
    options: {{ responsive:true, maintainAspectRatio:false,
      plugins: {{ legend:{{display:false}}, tooltip:{{callbacks:{{label:c=>fmtInr(c.raw)}}}} }},
      scales: {{ x:{{ticks:{{color:'#666',maxTicksLimit:20,font:{{size:8}}}},grid:{{display:false}}}},
        y:{{ticks:{{color:'#888',callback:v=>fmtInr(v)}},grid:{{color:'#ffffff10'}}}} }}
    }}
  }});

  return cfgs;
}}

const TILES = [
  {{key:'equity',    title:'Equity Curves',        sub:"Portfolio value over time for each strategy", tall:true, full:true}},
  {{key:'drawdowns', title:'Drawdowns',            sub:"% fall from each strategy's peak — measures pain during downturns", full:true}},
  {{key:'regime',    title:'Regime Returns',       sub:"How each strategy performed in different market conditions (NAV-based)"}},
  {{key:'cash',      title:'Cash Utilization',     sub:"% of portfolio actually deployed — lower = cash sitting idle"}},
  {{key:'alpha',     title:'Rolling Alpha vs SIP', sub:"How much Timed HODL beats SIP over rolling windows — positive = outperforming"}},
  {{key:'buydist',   title:'Buy Distribution',     sub:"Which stocks got the most buy signals (top 30)", tall:true}},
  {{key:'timeline',  title:'Monthly Deployment',   sub:"Amount deployed each month — gaps are idle cash periods", full:true}},
];

function openChartModal(key, title, sub) {{
  const ov = document.getElementById('chartModalOverlay');
  document.getElementById('chartModalTitle').textContent = title;
  document.getElementById('chartModalSub').textContent = sub || '';
  ov.classList.add('active');

  if (window._chartModalInstance) {{
    window._chartModalInstance.destroy();
    window._chartModalInstance = null;
  }}
  const cfgs = buildChartConfigs();
  const canvas = document.getElementById('chartModalCanvas');
  // Small defer so the canvas has real size from the flex wrap before Chart measures it
  requestAnimationFrame(() => {{
    window._chartModalInstance = new Chart(canvas, cfgs[key]());
  }});
}}

function closeChartModal() {{
  document.getElementById('chartModalOverlay').classList.remove('active');
  if (window._chartModalInstance) {{
    window._chartModalInstance.destroy();
    window._chartModalInstance = null;
  }}
}}

function renderBacktest() {{
  if (!BT) return;
  window._btRendered = true;
  const el = document.getElementById('bt_content');
  const a = BT.assumptions;
  const s = BT.summary;
  const colors = BT.strategy_colors;

  // Assumptions
  let html = `<div class="assumptions">
    <strong>Period:</strong> ${{a.start_date}} to ${{a.end_date}} (${{a.years}} years) &bull;
    <strong>Salary:</strong> ₹${{a.start_salary.toLocaleString()}}/mo → ₹${{a.end_salary.toLocaleString()}}/mo (${{a.hike_pct}}% hike) &bull;
    <strong>SIP:</strong> ₹${{a.start_monthly_sip.toLocaleString()}} → ₹${{a.end_monthly_sip.toLocaleString()}} (${{a.invest_pct}}% of salary) &bull;
    <strong>Invested:</strong> ${{fmtInr(BT.total_invested)}} &bull;
    <strong>Inflation:</strong> ${{a.inflation_rate}}%/yr (₹1 in ${{a.start_date.slice(0,4)}} ≈ ₹${{a.inflation_factor}} today)
  </div>`;

  // Summary cards
  const timed = BT.metrics[0];
  html += `<div class="summary-grid">
    <div class="stat-card"><div class="label">Final Value (Timed HODL)</div>
      <div class="value positive">${{fmtInr(timed.final_value)}}</div></div>
    <div class="stat-card"><div class="label">XIRR</div>
      <div class="value" style="color:#fff">${{timed.xirr.toFixed(1)}}%</div></div>
    <div class="stat-card"><div class="label">Wealth Multiple</div>
      <div class="value" style="color:var(--accent)">${{(timed.final_value/BT.total_invested).toFixed(1)}}x</div></div>
    <div class="stat-card"><div class="label">Sharpe / Sortino</div>
      <div class="value" style="color:#fff">${{timed.sharpe.toFixed(2)}} / ${{timed.sortino.toFixed(2)}}</div></div>
    <div class="stat-card"><div class="label">Max Drawdown</div>
      <div class="value negative">${{timed.max_drawdown.toFixed(1)}}%</div></div>
    <div class="stat-card"><div class="label">Buy Signals / Stocks</div>
      <div class="value" style="color:#fff">${{s.n_signals}} / ${{s.n_stocks_bought}}</div></div>
  </div>`;

  // Chart tiles grid — click any to zoom
  html += `<div style="color:var(--muted);font-size:0.78rem;margin-bottom:8px;text-align:right">
    Click any chart to zoom in</div>`;
  html += `<div class="bt-grid">`;
  TILES.forEach(t => {{
    const cls = `bt-tile${{t.tall ? ' tall' : ''}}${{t.full ? ' full' : ''}}`;
    html += `<div class="${{cls}}" onclick="openChartModal('${{t.key}}', '${{t.title}}', \`${{t.sub}}\`)">
      <span class="zoom-icon">&#x2922;</span>
      <h3>${{t.title}}</h3>
      <div class="chart-sub">${{t.sub}}</div>
      <div class="chart-wrap"><canvas id="bt_tile_${{t.key}}"></canvas></div>
    </div>`;
  }});
  html += `</div>`;

  // Metrics table
  html += `<div class="chart-card" style="margin-top:0"><h3>Performance Comparison</h3>
    <div style="overflow-x:auto"><table class="metrics-table"><thead><tr><th class="row-label"></th>`;
  BT.metrics.forEach(m => {{
    const c = colors[m.name] || '#fff';
    html += `<th style="color:${{c}}">${{m.name}}</th>`;
  }});
  html += `</tr></thead><tbody>`;

  const infl = a.inflation_factor;
  const mrows = [
    ['Final Value', m => fmtInr(m.final_value), 'max'],
    ['Inflation-Adj Value', m => fmtInr(m.final_value / infl), 'max'],
    ['Wealth Multiple', m => (m.final_value/BT.total_invested).toFixed(1)+'x', 'max'],
    ['XIRR', m => isNaN(m.xirr) ? '—' : m.xirr.toFixed(1)+'%', 'max'],
    ['Real XIRR (−6% infl)', m => isNaN(m.xirr) ? '—' : (m.xirr-a.inflation_rate).toFixed(1)+'%', 'max'],
    ['Sharpe Ratio', m => m.sharpe.toFixed(2), 'max'],
    ['Sortino Ratio', m => m.sortino.toFixed(2), 'max'],
    ['Max Drawdown', m => m.max_drawdown.toFixed(1)+'%', 'max'],
    ['Max DD Duration', m => m.max_dd_days+' days', 'min'],
    ['Volatility', m => m.volatility.toFixed(1)+'%', 'min'],
    ['Best Day', m => (m.best_day>=0?'+':'')+m.best_day.toFixed(1)+'%', null],
    ['Worst Day', m => m.worst_day.toFixed(1)+'%', null],
  ];

  mrows.forEach(([label, fn, bestFn]) => {{
    html += `<tr><td class="row-label">${{label}}</td>`;
    const vals = BT.metrics.map(fn);
    let bestIdx = -1;
    if (bestFn) {{
      const nums = BT.metrics.map(m => {{
        try {{ return parseFloat(fn(m)); }} catch {{ return NaN; }}
      }});
      const valid = nums.filter(n => !isNaN(n));
      if (valid.length) {{
        const target = bestFn === 'max' ? Math.max(...valid) : Math.min(...valid);
        bestIdx = nums.indexOf(target);
      }}
    }}
    vals.forEach((v, i) => {{
      const cls = i === bestIdx ? ' class="metrics-best"' : '';
      const c = i === bestIdx ? ` style="color:${{colors[BT.metrics[i].name] || '#fff'}}"` : '';
      html += `<td${{cls}}${{c}}>${{v}}</td>`;
    }});
    html += `</tr>`;
  }});
  html += `</tbody></table></div></div>`;

  el.innerHTML = html;

  // Render tile charts from the config registry
  const cfgs = buildChartConfigs();
  TILES.forEach(t => {{
    const canvas = document.getElementById('bt_tile_' + t.key);
    if (!canvas) return;
    window._btTileCharts[t.key] = new Chart(canvas, cfgs[t.key]());
  }});
}}
</script>
</body>
</html>"""
    return html


# ─── Main ──────────────────────────────────────────────────────────────────

def main():
    print("Loading trades...")
    holdings, trades_by_stock = load_holdings()
    print(f"Found {len(holdings)} stocks in {STRATEGY} strategy")

    print("Fetching current prices...")
    prices = fetch_current_prices(holdings["stock"].tolist())

    portfolio = build_portfolio(holdings, prices)
    valid = portfolio.dropna(subset=["current_price"])
    skipped = portfolio[portfolio["current_price"].isna()]
    if len(skipped):
        print(f"  Skipped {len(skipped)} stocks (no price data): {', '.join(skipped['stock'])}")

    portfolio_data = build_portfolio_json(valid, trades_by_stock)

    backtest_data = None
    try:
        with open(BACKTEST_JSON, "r") as f:
            backtest_data = json.load(f)
        print(f"  Loaded backtest data from {BACKTEST_JSON}")
    except FileNotFoundError:
        print(f"  No backtest data found ({BACKTEST_JSON}), skipping backtest tab")

    html = generate_html(portfolio_data, backtest_data)
    out_path = "dashboard.html"
    with open(out_path, "w") as f:
        f.write(html)
    print(f"  Dashboard saved -> {out_path}")


if __name__ == "__main__":
    main()
